/**
 * @module code
 *
 * @description
 * defines the values of CODE, which are used for programming control flow
 *
 * @author Hans-Peter Görg
 **/
exports.CODE = {
    OK: 'OK',
    WRONG_VERSION: 'WRONG_VERSION',
    MAX_COUNT_EXCEEDED: 'MAX_COUNT_EXCEEDED',
    NO_ENTRY_FOUND: 'NO_ENTRY_FOUND',
    NO_ENTRIES_FOUND: 'NO_ENTRIES_FOUND',
    DB_ERROR_OCCURRED: 'DB_ERROR_OCCURRED',
    DUPLICATE_KEY: 'DUPLICATE_KEY',
    INVALID_PASSWORD: 'INVALID_PASSWORD',
    INVALID_MONGODB_OBJECTID_FORMAT: 'INVALID_MONGODB_OBJECTID_FORMAT',
    INVALID_MONGODB_VERSION_FORMAT: 'INVALID_MONGODB_VERSION_FORMAT',
    INVALID_MONGODB_SCHEMA: 'INVALID_MONGODB_SCHEMA',
    SERVER_ERROR: 'SERVER_ERROR',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    TOKEN_ERROR: 'TOKEN_ERROR',
    TOKEN_DELIVERY_ERROR: 'TOKEN_DELIVERY_ERROR',
    FORCED_LOGOUT: 'FORCED_LOGOUT'
};
